framework:
    workflows:
        ton_macron_invitation:
            type: state_machine
            supports: [AppBundle\TonMacron\InvitationProcessor]
            places:
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_SENT
            transitions:
                !php/const AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                !php/const AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_PROJECT:
                    from:
                        - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                    to: !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                !php/const AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_INTERESTS:
                    from:
                        - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                    to: !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                !php/const AppBundle\TonMacron\InvitationProcessor::TRANSITION_FILL_REASONS:
                    from:
                        - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                    to: !php/const AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                !php/const AppBundle\TonMacron\InvitationProcessor::TRANSITION_SEND:
                    from:
                        - !php/const AppBundle\TonMacron\InvitationProcessor::STATE_SUMMARY
                    to: !php/const AppBundle\TonMacron\InvitationProcessor::STATE_SENT
        my_europe:
            type: state_machine
            supports: [AppBundle\Interactive\MyEuropeProcessor]
            places:
                - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_SUMMARY
                - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_SENT
            transitions:
                !php/const AppBundle\Interactive\MyEuropeProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                !php/const AppBundle\Interactive\MyEuropeProcessor::TRANSITION_FILL_CASES:
                    from:
                        - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                    to: !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                !php/const AppBundle\Interactive\MyEuropeProcessor::TRANSITION_FILL_APPRECIATIONS:
                    from:
                        - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                    to: !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_SUMMARY
                !php/const AppBundle\Interactive\MyEuropeProcessor::TRANSITION_SEND:
                    from:
                        - !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_SUMMARY
                    to: !php/const AppBundle\Interactive\MyEuropeProcessor::STATE_SENT

        assessor_request:
            type: state_machine
            initial_place: !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
            supports: [AppBundle\Assessor\AssessorRequestCommand]
            places:
                - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SUMMARY
                - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SENT
            transitions:
                !php/const AppBundle\Assessor\AssessorRequestEnum::TRANSITION_FILL_PERSONAL_INFO:
                    from:
                        - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                    to: !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const AppBundle\Assessor\AssessorRequestEnum::TRANSITION_FILL_ASSESSOR_INFO:
                    from:
                        - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to: !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SUMMARY

                !php/const AppBundle\Assessor\AssessorRequestEnum::TRANSITION_VALID_SUMMARY:
                    from:
                        - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to: !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SENT

                !php/const AppBundle\Assessor\AssessorRequestEnum::TRANSITION_BACK_ASSESSOR_INFO:
                    from:
                        - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to : !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const AppBundle\Assessor\AssessorRequestEnum::TRANSITION_BACK_PERSONAL_INFO:
                    from:
                        - !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to : !php/const AppBundle\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
